# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: 'Copy files to target folder'
  inputs:
    SourceFolder: $(build.sourcesdirectory)
    Contents: |
     **/*.war
     *.json
    TargetFolder: $(build.artifactstagingdirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    ArtifactName: drop


- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'

# - task: DownloadPipelineArtifact@2
#   displayName: 'Download pipeline artifacts'
#   inputs:
#     source: 'current'
#     artifactName: 'drop'
#     targetPath: $(System.ArtifactsDirectory)

- task: AzureKeyVault@2
  displayName: 'Azure Key Vault: kval '
  inputs:
    azureSubscription: AzureRM
    KeyVaultName: 'kval'

- task: AzureResourceGroupDeployment@2
  displayName: 'Resource Deployment'
  inputs:
    azureSubscription: AzureRM
    action: Create Or Update Resource Group
    resourceGroupName: $(resourcegroup)
    location: 'East US 2'
    templateLocation: Linked artifact
    csmFileLink: $(System.ArtifactsDirectory)/**/azurepolicy.json
    overrideParameters: -webAppName $(webappName) -mySQLAdminLoginName "azureuser" -mySQLAdminLoginPassword $(sqldbpassword)
    deploymentMode: Complete
    enableDeploymentPrerequisites: None

- task: AzureWebApp@1
  displayName: 'deploy to webapp'
  inputs:
    azureSubscription: AzureRM
    appType: webApp
    appName: $(webappName)
    package: $(System.ArtifactsDirectory)/**/*.war